#IT IS DESTINED FOR WHOMEVER MESSES THE HASH INDENTATION TO HAVE A LONG LIFE OF SUFFERING AND MISREY!

#----- THRUSTERS ---------------#
FRONT_RIGHT_PCA_CHANNEL: 1
FRONT_LEFT_PCA_CHANNEL: 0
BACK_LEFT_PCA_CHANNEL: 2
BACK_RIGHT_PCA_CHANNEL: 5
FRONT_PCA_CHANNEL: 3
BACK_PCA_CHANNEL: 4
#----- LEFT GRIPPER ------------#
# DC_LEFT_GPIO: 8
# DC_LEFT_PCA_CHANNEL: 11
# LEFTGRIPPER_UP_SERVO: 11
LEFT_GRIPPER_SWITCH: 16
#------ VERTICAL GRIPPER ----------#
DC_VERTICALGRIPPER_GPIO: 8
DC_VERTICALGRIPPER_PCA_CHANNEL: 9
VERTICALGRIPPER_SWITCH: 25
#------ FRONT GRIPPER ----------#
FRONTGRIPPER_SWITCH: 26
DC_FRONTGRIPPER_PCA_CHANNEL: 11
DC_FRONTGRIPPER_GPIO: 6
#------ FLASH ------------------#
LEFTGRIPPER_UP_DOWN_SWITCH: 12
#------ SERVO-------------------#
SERVO_CHANNEL: 6
STEREO_SERVO: 7
PHOTOSPHERE_SERVO: 14
#------ SYRINGE-----------------#
SYRINGE_SWITCH: 16
#------ RAIN -------------------#
RAIN_GPIO: 1